name: Java

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 13
        uses: actions/setup-java@v1
        with:
          java-version: 13
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Build executable jars
        run: mvn -B -P executable install --file pom.xml
      - name: Releasing executable Generator jar
        uses: actions/upload-artifact@v2
        with:
          name: generator.jar
          path: generator/target/inf5153.mesh.generator-1.0-jar-with-dependencies.jar
      - name: Releasing executable Visualizer jar
          uses: actions/upload-artifact@v2
          with:
            name: visualizer.jar
            path: visualizer/target/inf5153.mesh.visualizer-1.0-jar-with-dependencies.jar